### ISSUE TITLE
cudnn_relu_layer.cpp:13] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR *** Check failure stack trace: *** Aborted (core dumped)

### ISSUE THREAD

**Issue by monajalal** [rbgirshick/py-faster-rcnn#311]
Do you know how to fix this?
I have CuDNN v4, Cuda 7.5, Ubuntu 15.10 and Python2.7:
```
 ./tools/demo.py

BLAH BLAH 

I0823 20:13:31.513314 40008 layer_factory.hpp:77] Creating layer conv5_1
I0823 20:13:31.513336 40008 net.cpp:106] Creating Layer conv5_1
I0823 20:13:31.513351 40008 net.cpp:454] conv5_1 <- pool4
I0823 20:13:31.513361 40008 net.cpp:411] conv5_1 -> conv5_1
I0823 20:13:31.522544 40008 net.cpp:150] Setting up conv5_1
I0823 20:13:31.522575 40008 net.cpp:157] Top shape: 1 512 14 14 (100352)
I0823 20:13:31.522591 40008 net.cpp:165] Memory required for data: 112394240
I0823 20:13:31.522610 40008 layer_factory.hpp:77] Creating layer relu5_1
I0823 20:13:31.522629 40008 net.cpp:106] Creating Layer relu5_1
I0823 20:13:31.522644 40008 net.cpp:454] relu5_1 <- conv5_1
I0823 20:13:31.522662 40008 net.cpp:397] relu5_1 -> conv5_1 (in-place)
I0823 20:13:31.522843 40008 net.cpp:150] Setting up relu5_1
I0823 20:13:31.522869 40008 net.cpp:157] Top shape: 1 512 14 14 (100352)
I0823 20:13:31.522883 40008 net.cpp:165] Memory required for data: 112795648
I0823 20:13:31.522891 40008 layer_factory.hpp:77] Creating layer conv5_2
I0823 20:13:31.522902 40008 net.cpp:106] Creating Layer conv5_2
I0823 20:13:31.522909 40008 net.cpp:454] conv5_2 <- conv5_1
I0823 20:13:31.522922 40008 net.cpp:411] conv5_2 -> conv5_2
I0823 20:13:31.529803 40008 net.cpp:150] Setting up conv5_2
I0823 20:13:31.529841 40008 net.cpp:157] Top shape: 1 512 14 14 (100352)
I0823 20:13:31.529849 40008 net.cpp:165] Memory required for data: 113197056
I0823 20:13:31.529868 40008 layer_factory.hpp:77] Creating layer relu5_2
I0823 20:13:31.529887 40008 net.cpp:106] Creating Layer relu5_2
I0823 20:13:31.529903 40008 net.cpp:454] relu5_2 <- conv5_2
I0823 20:13:31.529920 40008 net.cpp:397] relu5_2 -> conv5_2 (in-place)
F0823 20:13:31.530177 40008 cudnn_relu_layer.cpp:13] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
Aborted (core dumped)

```
I have successfully done all the steps before this!

**Comment by monajalal** [comment]
My issue was resolved after installing the software on a machine with Tesla K40 GPU (12 GB SDRAM). The previous machine has a 81:00.0 VGA compatible controller: NVIDIA Corporation GK208 [GeForce GT 730] (rev a1) which is from Kepler family.

**Comment by muyue1238** [comment]
hi, I ran into the same error and couldn't solve it, could you tell me why this error happened? Thank you so much!

**Comment by tongpinmo** [comment]
@monajalal have you ever solve it?

**Comment by muyue1238** [comment]
@monajalal Hi there. My problem solved but I'm not really sure how it's solved. I'm using anaconda and I reinstall it when some problem happened and I couldn't find the solution.
