### ISSUE TITLE
ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by monajalal** [rbgirshick/py-faster-rcnn#372]
I get the following error for CUDA8 installed on my machine:

```
mona@pascal:~/computer_vision/py-faster-rcnn$ ./tools/demo.py
Traceback (most recent call last):
  File "./tools/demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/fast_rcnn/nms_wrapper.py", line 9, in <module>mona@pascal:~/computer_vision/py-faster-rcnn$ ./tools/demo.py
Traceback (most recent call last):
  File "./tools/demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "/home/mona/computer_vision/py-faster-rcnn/tools/../lib/fast_rcnn/nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory

    from nms.gpu_nms import gpu_nms
ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory

```

Also cudnn v5 didn't work so I had to disable it. 
How can I fix this?

and I have:

```
mona@pascal:~/computer_vision/py-faster-rcnn$ sudo ldconfig /usr/local/cuda/lib64
[sudo] password for mona: 
/sbin/ldconfig.real: /usr/local/cuda/lib64/libcudnn.so.5 is not a symbolic link
```

**Comment by hgaiser** [comment]
Seems it is still linked against cuda 7, I'm assuming you had that installed before? Recompile the faster-rcnn code.

**Comment by monajalal** [comment]
I did 
make 
and make install
however getting the error again.
I guess I am going to have the folder rm -rf and see what happens

**Comment by hgaiser** [comment]
I'm assuming cuda 7 is no longer installed ?

**Comment by monajalal** [comment]
no it is not installed. does pyfaster rnn work with cudnn 5 anyways?

**Comment by hgaiser** [comment]
I believe it requires a modified caffe-fastrcnn with updates from upstream
caffe, but yeah if you go through that trouble it works.

**Comment by monajalal** [comment]
the way I fixed it was deleting the whole directory getting it again from github and things worked fine. 

Also it didn't work with cudnn=5 hence I had to disable it :-1:

**Comment by ZhengRui** [comment]
delete the `.so` files inside lib folders and `make` again inside lib folder solve my issue

**Comment by jamiechoi1995** [comment]
> 
> 
> delete the `.so` files inside lib folders and `make` again inside lib folder solve my issue

it should be the lib/nms folder
