### ISSUE TITLE
How to make with cuDNN?

### ISSUE THREAD

**Issue by JohnnyY8** [rbgirshick/py-faster-rcnn#383]
Hi everyone:
   I want to run make command in "py-faster_rcnn/caffe-fast-rcnn" with CUDA-8.0 and cudnn-8.0-linux-x64-v5.1, but got some errors like following:
![image](https://cloud.githubusercontent.com/assets/12611573/19710374/70e7835e-9b60-11e6-8c30-925a6ec61fa6.png)
  I have run these command for copying cudnn files:
  cp include/cudnn.h /usr/local/include/
  cp lib64/libcudnn.\* /usr/local/lib/
  sudo ln -sf /usr/local/lib/libcudnn.so.5.1.3 /usr/local/lib/libcudnn.so.5
  sudo ln -sf /usr/local/lib/libcudnn.so.5 /usr/local/lib/libcudnn.so
  sudo ldconfig

  I do not know how to fix it? Can anyone help me?
  Thanks a lot!

**Comment by pham93** [comment]
issue solved here
https://github.com/rbgirshick/py-faster-rcnn/issues/237

**Comment by JohnnyY8** [comment]
@pham93 Thanks a lot. It works for me.

**Comment by ravikantb** [comment]
@JohnnyY8 @pham93 : 
Can someone comment on the performance of using py-faster-rcnn with following setup:
CUDA version: 8.0
cudnn version: 5.0.5
GPU: Nvidia 1080 Pascal architecture

My previous setup of original py-faster-rcnn (i.e. without merging it with latest caffe) used to train at least twice as fast on CUDA-7.5, cudnn-3.0 and Nvidia TitanX Maxwell architecture.

Is there any FP16 computation going on in there which is slower on 1080 as compared to TitanX ?

**Comment by JohnnyY8** [comment]
@ravikantb Hi:
I am not quite sure about the performance between 1080 and TitanX Maxwell aitecture. 
Our environment is CUDA 8.0, cuDNN v5.1, and TitanX **pascal architecture**. There are some strange situations, our caffe is slower than 1080, but our py-faster-rcnn is faster than 1080. I do not know why exactly.

**Comment by xinleipan** [comment]
@JohnnyY8 How do you manage to make it work on cuda 8.0 and cuDNN v5.1 with Titan X pascal architecture? Could you give the Makefile.config and the way you installed this? Thank you!

**Comment by JohnnyY8** [comment]
@xinleipan Hi:
I am sorry for replying late. I manage to make it according to #237 :
```
cd caffe-fast-rcnn  
git remote add caffe https://github.com/BVLC/caffe.git  
git fetch caffe  
git merge caffe/master 
```
Hope it can help you.

**Comment by vguptai** [comment]
@xinleipan Hope this can help:

https://medium.com/@vikram.gupta/fixing-py-faster-rcnn-for-cudnn5-a7993d3ff3a1
