### ISSUE TITLE
Error at Iteration 3300 when training on custom dataset

### ISSUE THREAD

**Issue by LiberiFatali** [rbgirshick/py-faster-rcnn#85]
Hi, I use py-faster-rcnn to train on my dataset. Data was prepapred correctly and when I call `./experiments/scripts/faster_rcnn_end2end.sh 1 VGG_CNN_M_1024`, it runs well until  

```
Iteration 3300, lr = 0.001
F0219 17:16:44.484053 30335 cudnn_conv_layer.cu:53] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
```

If I compile caffe-fast-rcnn without CuDNN (comment USE_CUDNN := 1 in Makefile.config), I got
```
Iteration 3300, lr = 0.001
F0219 17:34:20.377171 10728 pooling_layer.cu:213] Check failed: error == cudaSuccess (9 vs. 0)  invalid configuration argument
```
I tried to reduce RPN_BATCHSIZE and BATCH_SIZE, IMS_PER_BATCH: 1 ; still got this error

My training images were cropped on target object, so I set coordinates in annotation files as `10, 10, width-10, height-10`
It was running well until Iteration 3300. 

The GPU is GeForce GTX TITAN X. Ubuntu 14.04, CUDA 7.0 and cudnn-6.5-linux-x64-v2.

Any help is appreciated. Thank you !

**Comment by LiberiFatali** [comment]
It turns out that there are some big images in my training set. When I remove big size images, network is trained well.

**Comment by LiberiFatali** [comment]
Removed images which have big ratio between height and width solve this problem.

**Comment by sohamghoshmusigma** [comment]
HI @LiberiFatali,

I'm getting a very similar issue with my 2GB gpu, so I tried reducing the RPN_BATCHSIZE from the  **experiments/cfgs/faster_rcnn_end2end.yml**

I also went to search for the BATCH_SIZE in some file, except I'm having some doubts here, would you mind helping me out here?

The constant appears only in couple of places, first it appears in the build files in some places like: **caffe-fast-rcnn/src/caffe/proto/caffe.proto:    BATCH_SIZE = 2;**

GIven that it has batch size as 2, I thought that the only other place it exists as a higher number is **lib/fast_rcnn/config.py:__C.TRAIN.BATCH_SIZE = 128**

When I went to edit this file, it said that I shouldn't edit it by hand, and instead convert a yml to it. Could you help me out in this procedure?

My exact error is:

**F0511 14:37:40.936714 13120 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory**

**Comment by LiberiFatali** [comment]
In my case: "Removed images which have big ratio between height and width solve this problem.". So you may look into your training set and try to normalize the images size/ratio first

**Comment by sohamghoshmusigma** [comment]
I did, I don't have any images that have a great ratio. So I was wondering If you could tell me how you changed the batch size parameter, I wanted to give that a try so I could be sure the problem lies else where. I'm guessing you changed the other two parameters in the **experiments/cfgs/faster_rcnn_end2end.yml** file. Also can you tell me if you have to make the library again after you change the parameters? That should be the case, right?

**Comment by LiberiFatali** [comment]
You don't need to compile/make the library again. That `.yml` config file is used in `faster_rcnn_end2end.sh`

**Comment by tongpinmo** [comment]
@LiberiFatali   the images in the demo are not so big,width is about 500 pixels,and the height is about 400 pixels,so how to change the ratio???  I have only two images

**Comment by LiberiFatali** [comment]
"width is about 500 pixels,and the height is about 400 pixels" <-- so I think you don't need to resize or change it ratio.

**Comment by NIRAJ-GOEL03** [comment]
@LiberiFatali  Hi I am getting the same error, however I get it while the network is setting up, specifically when the rpn_conv layer's setup starts. As per your suggestion I tried removing all the images with high size ratio (removed everything with ratio > 1.4) but the error is still coming. 

I am trying to perform domain adaption for which I have modified the prototxt file to take input as source data and target data. source data is voc images and target data is custom dataset (unannotated). When I run the setup just with voc dataset i.e. without my changes of domain adaption, it runs fine (atleast it starts the training iterations).
Any idea what might be the issue ? Any sort of help would be appreciated. Thanks in advance !

![image](https://user-images.githubusercontent.com/2663376/39286287-b0029e4e-48e2-11e8-9a0e-1be40ddd339c.png)
